<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.0" name="main" tilewidth="176" tileheight="202" tilecount="148" columns="0">
 <grid orientation="orthogonal" width="1" height="1"/>
  <tile id="0"><image source="air.png" width="176" height="202"/></tile>
  <tile id="1"><image source="acacia_leaves.png" width="176" height="202"/></tile>
  <tile id="2"><image source="acacia_log.png" width="176" height="202"/></tile>
  <tile id="3"><image source="acacia_planks.png" width="176" height="202"/></tile>
  <tile id="4"><image source="amethyst_block.png" width="176" height="202"/></tile>
  <tile id="5"><image source="ancient_debris.png" width="176" height="202"/></tile>
  <tile id="6"><image source="andesite.png" width="176" height="202"/></tile>
  <tile id="7"><image source="barrel.png" width="176" height="202"/></tile>
  <tile id="8"><image source="basalt.png" width="176" height="202"/></tile>
  <tile id="9"><image source="bedrock.png" width="176" height="202"/></tile>
  <tile id="10"><image source="birch_leaves.png" width="176" height="202"/></tile>
  <tile id="11"><image source="birch_log.png" width="176" height="202"/></tile>
  <tile id="12"><image source="birch_planks.png" width="176" height="202"/></tile>
  <tile id="13"><image source="blackstone.png" width="176" height="202"/></tile>
  <tile id="14"><image source="black_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="15"><image source="black_wool.png" width="176" height="202"/></tile>
  <tile id="16"><image source="blast_furnace.png" width="176" height="202"/></tile>
  <tile id="17"><image source="blue_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="18"><image source="blue_wool.png" width="176" height="202"/></tile>
  <tile id="19"><image source="bricks.png" width="176" height="202"/></tile>
  <tile id="20"><image source="brown_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="21"><image source="brown_wool.png" width="176" height="202"/></tile>
  <tile id="22"><image source="chiseled_red_sandstone.png" width="176" height="202"/></tile>
  <tile id="23"><image source="chiseled_sandstone.png" width="176" height="202"/></tile>
  <tile id="24"><image source="chiseled_stone_bricks.png" width="176" height="202"/></tile>
  <tile id="25"><image source="clay.png" width="176" height="202"/></tile>
  <tile id="26"><image source="coal_block.png" width="176" height="202"/></tile>
  <tile id="27"><image source="coal_ore.png" width="176" height="202"/></tile>
  <tile id="28"><image source="coarse_dirt.png" width="176" height="202"/></tile>
  <tile id="29"><image source="cobbled_deepslate.png" width="176" height="202"/></tile>
  <tile id="30"><image source="cobblestone.png" width="176" height="202"/></tile>
  <tile id="31"><image source="copper_block.png" width="176" height="202"/></tile>
  <tile id="32"><image source="copper_ore.png" width="176" height="202"/></tile>
  <tile id="33"><image source="cracked_deepslate_tiles.png" width="176" height="202"/></tile>
  <tile id="34"><image source="cracked_nether_bricks.png" width="176" height="202"/></tile>
  <tile id="35"><image source="cracked_polished_blackstone_bricks.png" width="176" height="202"/></tile>
  <tile id="36"><image source="cracked_stone_bricks.png" width="176" height="202"/></tile>
  <tile id="37"><image source="crafting_table.png" width="176" height="202"/></tile>
  <tile id="38"><image source="cyan_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="39"><image source="cyan_wool.png" width="176" height="202"/></tile>
  <tile id="40"><image source="dark_oak_leaves.png" width="176" height="202"/></tile>
  <tile id="41"><image source="dark_oak_log.png" width="176" height="202"/></tile>
  <tile id="42"><image source="dark_oak_planks.png" width="176" height="202"/></tile>
  <tile id="43"><image source="deepslate.png" width="176" height="202"/></tile>
  <tile id="44"><image source="deepslate_bricks.png" width="176" height="202"/></tile>
  <tile id="45"><image source="deepslate_coal_ore.png" width="176" height="202"/></tile>
  <tile id="46"><image source="deepslate_copper_ore.png" width="176" height="202"/></tile>
  <tile id="47"><image source="deepslate_diamond_ore.png" width="176" height="202"/></tile>
  <tile id="48"><image source="deepslate_emerald_ore.png" width="176" height="202"/></tile>
  <tile id="49"><image source="deepslate_gold_ore.png" width="176" height="202"/></tile>
  <tile id="50"><image source="deepslate_iron_ore.png" width="176" height="202"/></tile>
  <tile id="51"><image source="deepslate_lapis_ore.png" width="176" height="202"/></tile>
  <tile id="52"><image source="deepslate_redstone_ore.png" width="176" height="202"/></tile>
  <tile id="53"><image source="deepslate_tiles.png" width="176" height="202"/></tile>
  <tile id="54"><image source="diamond_block.png" width="176" height="202"/></tile>
  <tile id="55"><image source="diamond_ore.png" width="176" height="202"/></tile>
  <tile id="56"><image source="diorite.png" width="176" height="202"/></tile>
  <tile id="57"><image source="dirt.png" width="176" height="202"/></tile>
  <tile id="58"><image source="emerald_block.png" width="176" height="202"/></tile>
  <tile id="59"><image source="end_stone.png" width="176" height="202"/></tile>
  <tile id="60"><image source="end_stone_bricks.png" width="176" height="202"/></tile>
  <tile id="61"><image source="farmland_moist.png" width="176" height="202"/></tile>
  <tile id="62"><image source="farmland.png" width="176" height="202"/></tile>
  <tile id="63"><image source="furnace.png" width="176" height="202"/></tile>
  <tile id="64"><image source="glass.png" width="176" height="202"/></tile>
  <tile id="65"><image source="gold_block.png" width="176" height="202"/></tile>
  <tile id="66"><image source="gold_ore.png" width="176" height="202"/></tile>
  <tile id="67"><image source="granite.png" width="176" height="202"/></tile>
  <tile id="68"><image source="grass.png" width="176" height="202"/></tile>
  <tile id="69"><image source="gravel.png" width="176" height="202"/></tile>
  <tile id="70"><image source="gray_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="71"><image source="gray_wool.png" width="176" height="202"/></tile>
  <tile id="72"><image source="green_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="73"><image source="green_wool.png" width="176" height="202"/></tile>
  <tile id="74"><image source="iron_block.png" width="176" height="202"/></tile>
  <tile id="75"><image source="iron_ore.png" width="176" height="202"/></tile>
  <tile id="76"><image source="jukebox.png" width="176" height="202"/></tile>
  <tile id="77"><image source="jungle_leaves.png" width="176" height="202"/></tile>
  <tile id="78"><image source="jungle_log.png" width="176" height="202"/></tile>
  <tile id="79"><image source="jungle_planks.png" width="176" height="202"/></tile>
  <tile id="80"><image source="lapis_block.png" width="176" height="202"/></tile>
  <tile id="81"><image source="lapis_ore.png" width="176" height="202"/></tile>
  <tile id="82"><image source="light_blue_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="83"><image source="light_blue_wool.png" width="176" height="202"/></tile>
  <tile id="84"><image source="light_gray_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="85"><image source="light_gray_wool.png" width="176" height="202"/></tile>
  <tile id="86"><image source="lime_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="87"><image source="lime_wool.png" width="176" height="202"/></tile>
  <tile id="88"><image source="magenta_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="89"><image source="magenta_wool.png" width="176" height="202"/></tile>
  <tile id="90"><image source="melon.png" width="176" height="202"/></tile>
  <tile id="91"><image source="mycelium.png" width="176" height="202"/></tile>
  <tile id="92"><image source="oak_leaves.png" width="176" height="202"/></tile>
  <tile id="93"><image source="oak_log.png" width="176" height="202"/></tile>
  <tile id="94"><image source="oak_planks.png" width="176" height="202"/></tile>
  <tile id="95"><image source="orange_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="96"><image source="orange_wool.png" width="176" height="202"/></tile>
  <tile id="97"><image source="path.png" width="176" height="202"/></tile>
  <tile id="98"><image source="pink_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="99"><image source="pink_wool.png" width="176" height="202"/></tile>
  <tile id="100"><image source="prismarine_bricks.png" width="176" height="202"/></tile>
  <tile id="101"><image source="pumpkin.png" width="176" height="202"/></tile>
  <tile id="102"><image source="purple_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="103"><image source="purple_wool.png" width="176" height="202"/></tile>
  <tile id="104"><image source="purpur_block.png" width="176" height="202"/></tile>
  <tile id="105"><image source="purpur_pillar.png" width="176" height="202"/></tile>
  <tile id="106"><image source="quartz_block_bottom.png" width="176" height="202"/></tile>
  <tile id="107"><image source="quartz_block.png" width="176" height="202"/></tile>
  <tile id="108"><image source="quartz_bricks.png" width="176" height="202"/></tile>
  <tile id="109"><image source="quartz_pillar.png" width="176" height="202"/></tile>
  <tile id="110"><image source="redstone_block.png" width="176" height="202"/></tile>
  <tile id="111"><image source="redstone_ore.png" width="176" height="202"/></tile>
  <tile id="112"><image source="red_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="113"><image source="red_nether_bricks.png" width="176" height="202"/></tile>
  <tile id="114"><image source="red_sand.png" width="176" height="202"/></tile>
  <tile id="115"><image source="red_sandstone.png" width="176" height="202"/></tile>
  <tile id="116"><image source="red_wool.png" width="176" height="202"/></tile>
  <tile id="117"><image source="rooted_dirt.png" width="176" height="202"/></tile>
  <tile id="118"><image source="sand.png" width="176" height="202"/></tile>
  <tile id="119"><image source="sandstone.png" width="176" height="202"/></tile>
  <tile id="120"><image source="smithing_table.png" width="176" height="202"/></tile>
  <tile id="121"><image source="smoker.png" width="176" height="202"/></tile>
  <tile id="122"><image source="smooth_basalt.png" width="176" height="202"/></tile>
  <tile id="123"><image source="soul_sand.png" width="176" height="202"/></tile>
  <tile id="124"><image source="soul_soil.png" width="176" height="202"/></tile>
  <tile id="125"><image source="spawner.png" width="176" height="202"/></tile>
  <tile id="126"><image source="sponge.png" width="176" height="202"/></tile>
  <tile id="127"><image source="spruce_leaves.png" width="176" height="202"/></tile>
  <tile id="128"><image source="spruce_log.png" width="176" height="202"/></tile>
  <tile id="129"><image source="spruce_planks.png" width="176" height="202"/></tile>
  <tile id="130"><image source="stone.png" width="176" height="202"/></tile>
  <tile id="131"><image source="stone_bricks.png" width="176" height="202"/></tile>
  <tile id="132"><image source="stripped_acacia_log.png" width="176" height="202"/></tile>
  <tile id="133"><image source="stripped_birch_log.png" width="176" height="202"/></tile>
  <tile id="134"><image source="stripped_crimson_stem.png" width="176" height="202"/></tile>
  <tile id="135"><image source="stripped_dark_oak_log.png" width="176" height="202"/></tile>
  <tile id="136"><image source="stripped_jungle_log.png" width="176" height="202"/></tile>
  <tile id="137"><image source="stripped_oak_log.png" width="176" height="202"/></tile>
  <tile id="138"><image source="stripped_spruce_log.png" width="176" height="202"/></tile>
  <tile id="139"><image source="stripped_warped_stem.png" width="176" height="202"/></tile>
  <tile id="140"><image source="target.png" width="176" height="202"/></tile>
  <tile id="141"><image source="tnt.png" width="176" height="202"/></tile>
  <tile id="142"><image source="warped_nylium.png" width="176" height="202"/></tile>
  <tile id="143"><image source="warped_planks.png" width="176" height="202"/></tile>
  <tile id="144"><image source="white_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="145"><image source="white_wool.png" width="176" height="202"/></tile>
  <tile id="146"><image source="yellow_glazed_terracotta.png" width="176" height="202"/></tile>
  <tile id="147"><image source="yellow_wool.png" width="176" height="202"/></tile>
</tileset>
